---
language: generic
services: docker

script:
  - docker-compose run --rm latexmk manuscript.tex

deploy:
  provider: pages
  github-token: 
  file:
    - "*.pdf"
  keep_history: true
  skip_cleanup: true
  on:
    branch: master

