---
language: generic
services: docker

script:
  - docker-compose run --rm latexmk manuscript.tex

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "*.pdf"
  skip_cleanup: true
  on:
    branch:
      - master
      - ci_cd