---
language: generic
services: docker

script:
  - docker-compose run --rm latexmk manuscript.tex

deploy:
  provider: pages
  github-token: d74326051ec8228a9a9bfbac44f1003928b7fa2d
  file:
    - "*.pdf"
  keep_history: true
  skip_cleanup: true
  on:
    branch: master

