sudo: required
language: generic
services: docker

script:
  # We use the docker image from https://hub.docker.com/r/dxjoke/tectonic-docker/
  - docker pull dxjoke/tectonic-docker
  # Compiling only manuscript.tex:
  - docker run --mount src=4build/src,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic manuscript.tex"
  # Compiling multiple files as well as using biber:
#  - docker run --mount src=4build/src,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic --keep-intermediates --reruns 0 biber-mwe.tex; biber biber-mwe; tectonic biber-mwe.tex; tectonic manuscript.tex"
